### ISSUE TITLE
is there a wildcard for matrix indexing?

### ISSUE THREAD

**Issue by amuseoffire** [kyonifer/golem#25]
for instance something like

A[0..5,:]

?

or do I have to do

A[0..5,0 until numCols]

?

beautiful project. 

thanks.

**Comment by kyonifer** [comment]
Thanks for reporting.

I don't, but its definitely something that should be added. I'm considering:

```kotlin
A[0..3, 3..end]
A[0..3, all]
```

**Comment by amuseoffire** [comment]
those look great.

**Comment by amuseoffire** [comment]
looking good . . . might as well add a "begin" or "first" to complete the triangle.

**Comment by kyonifer** [comment]
My only concern there is that we'd be polluting the namespace with common identifiers, making it harder to import `golem.*`. I'd probably end up using `0..end` anyway since thats shorter than `start..end`. The current approach matches MATLAB's `1:end`, which would be good for people coming from that background.

I'd much prefer numpy's `A[:]` or MATLAB's `A(:)` syntax, but unfortunately Kotlin's syntax doesn't support anything like `A[5..]` or `A[,1..2]`

**Comment by amuseoffire** [comment]
apologies.  agreed that 0 is better than "first."
