### ISSUE TITLE
cross-reference to kplyr

### ISSUE THREAD

**Issue by holgerbrandl** [kyonifer/golem#3]
Hi kyonier, great lib! 
Since dataframe support still seems missing in golem, you maybe could add a reference to 
https://github.com/holgerbrandl/kplyr

**Comment by kyonifer** [comment]
Thanks, yours looks good too! I can definitely link back. 

I was also wondering if it might make sense to try to support some interop between our projects. It looks like you're doing something pretty similar to pandas, and I'm trying to take a hack at a numpy/matplotlib environment. It might be worth considering having kplyr return array numeric types in a numerical container similar to pandas returning numpy.ndarray. 

My current container is a 2D-only matrix container (limited to numerical types, due to the operations it supports) which wraps the various jvm 2D matrix backends. However, I'm planning to also write a NDArray container which is more general (initial work [here](https://github.com/kyonifer/golem/tree/ndarray)) which wraps the some of the various N-D options that we have on the jvm (maybe nd4j or vectorz) as well as potentially some more general solutions like the [new numpy ndarray base being worked on by continuum](https://github.com/libdynd/libdynd). What that container supports will mostly be a function of what those backends are able to provide consistently. Long term the 2D container will probably be focused on linear algebra and be a sub-class of the general ND type (which doesnt support 2D only operations, e.g. the matrix exponential). It looks like it should be possible to have the dynd backend support non-numeric NDArray since it has support for string.
